CREATE TABLE Cars (
	ID_Car INTEGER PRIMARY KEY NOT NULL,
	VIN VARCHAR(30) NOT NULL,
	Manufacturer VARCHAR(50) NOT NULL,
	Model VARCHAR(50) NOT NULL,
	Year INTEGER,
	Color VARCHAR(30)
);

CREATE TABLE Customers (
	ID_Customer INTEGER PRIMARY KEY NOT NULL,
	Customer_ID INTEGER NOT NULL,
	Name CHAR(30) NOT NULL,
	Phone VARCHAR(50) NOT NULL,
	Email VARCHAR(50),
	Address VARCHAR(100),
	City VARCHAR(30),
	State_province VARCHAR(50),
	Country VARCHAR(20),
	Postal INTEGER
);

CREATE TABLE Salespersons (
	ID_Salesperson INTEGER PRIMARY KEY NOT NULL,
	Staff_ID VARCHAR(30) NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Store VARCHAR(50) NOT NULL
);

CREATE TABLE Invoices (
	ID_Invoice INTEGER PRIMARY KEY NOT NULL,
	Invoice_number INTEGER,
	Date DATE,
	ID_Car INTEGER,
	ID_Customer INTEGER,
	ID_Salesperson INTEGER
);

SELECT * FROM Cars;
SELECT * FROM Customers;
SELECT * FROM Salespersons;
SELECT * FROM Invoices;
